language: go
go:
  - 1.18.x
go_import_path: k8s.restdev.com/operators
services:
  - docker
stages:
  - name: Testing
    script: make test OPERATOR=scaling
  - name: Dockerizing
    if: tag =~ ^[0-9]+.[0-9]+.[0-9]+$
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make build OPERATOR="scaling" VERSION="$TRAVIS_TAG"
    - make push OPERATOR="scaling" VERSION="$TRAVIS_TAG"
