#!/bin/bash

#########################################
## NOTE #################################
#########################################
##                                     ##
## Script uses the kubernodes cli (kn) ##
## http://npmjs.com/package/kubernodes ##
##                                     ##
#########################################

IMAGE=$1
K8S_RESTDEV_OPERATOR=$2
PROJECT_ID=$3
gcloud docker -- push $IMAGE
cat ./artifacts/kubes/$K8S_RESTDEV_OPERATOR/deployment.yml | sed "s|\[IMAGE\]|$IMAGE|g" | kn $PROJECT_ID -- --namespace=kube-system apply -f -
