/*
Copyright West Coast DevOps

Author: Eric Uldall
Repo:   https://github.com/West-Coast-Devops/scheduled-scaler

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ScheduledScalerListerExpansion allows custom methods to be added to
// ScheduledScalerLister.
type ScheduledScalerListerExpansion interface{}

// ScheduledScalerNamespaceListerExpansion allows custom methods to be added to
// ScheduledScalerNamespaceLister.
type ScheduledScalerNamespaceListerExpansion interface{}
