apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scheduled-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduled-scaler
subjects:
- kind: ServiceAccount
  name: scheduled-scaler
  namespace: kube-system
