apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: scheduledscalers.scaling.k8s.restdev.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: scaling.k8s.restdev.com
  versions:
    # version name to use for REST API: /apis/<group>/<version>
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                timeZone:
                  type: string
                target:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    apiVersion:
                      type: string
                  required: ["kind", "name", "apiVersion"]
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      runat:
                        type: string
                        pattern: "^(((\\d+|\\d+(-|\\/)\\d+)(,(\\d+|\\d+(-|\\/)\\d+))*|\\*) ){5}((\\d+|\\d+(-|\\/)\\d+)(,(\\d+|\\d+(-|\\/)\\d+))*|\\*)$"
                      mode:
                        type: string
                        pattern: "^(fixed|range)$"
                      replicas:
                        type: integer
                      minReplicas:
                        type: integer
                      maxReplicas:
                        type: integer
                    required: ["runat", "mode"]
              required: ["target", "steps"]
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: scheduledscalers
    # singular name to be used as an alias on the CLI and for display
    singular: scheduledscaler
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ScheduledScaler
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ss
