{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "scheduled-scaler.fullname" . }}
rules:
   # Allow scheduled-scaler controller full control on its CRD's group
- apiGroups: ["scaling.k8s.restdev.com"]
  resources: ["*"]
  verbs: ["*"]
  nonResourceURLs: []
  # Allow scheduled-scaler controller to list, get, update hpa in non-core APIs
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers", "horizontalpodautoscalers/status"]
  verbs: ["list", "get", "update"]
  nonResourceURLs: []
  # Allow scheduled-scaler controller to list, get, update hpa in extensions API
- apiGroups: ["extensions"]
  resources: ["horizontalpodautoscalers", "horizontalpodautoscalers/status"]
  verbs: ["list", "get", "update"]
  nonResourceURLs: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scheduled-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "scheduled-scaler.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "scheduled-scaler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "scheduled-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
