/*
Copyright West Coast DevOps

Author: Eric Uldall
Repo:   https://github.com/West-Coast-Devops/scheduled-scaler

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.restdev.com/operators/pkg/apis/scaling/v1alpha1"
	scheme "k8s.restdev.com/operators/pkg/client/clientset/versioned/scheme"
)

// ScheduledScalersGetter has a method to return a ScheduledScalerInterface.
// A group's client should implement this interface.
type ScheduledScalersGetter interface {
	ScheduledScalers(namespace string) ScheduledScalerInterface
}

// ScheduledScalerInterface has methods to work with ScheduledScaler resources.
type ScheduledScalerInterface interface {
	Create(ctx context.Context, scheduledScaler *v1alpha1.ScheduledScaler, opts v1.CreateOptions) (*v1alpha1.ScheduledScaler, error)
	Update(ctx context.Context, scheduledScaler *v1alpha1.ScheduledScaler, opts v1.UpdateOptions) (*v1alpha1.ScheduledScaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ScheduledScaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ScheduledScalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduledScaler, err error)
	ScheduledScalerExpansion
}

// scheduledScalers implements ScheduledScalerInterface
type scheduledScalers struct {
	client rest.Interface
	ns     string
}

// newScheduledScalers returns a ScheduledScalers
func newScheduledScalers(c *ScalingV1alpha1Client, namespace string) *scheduledScalers {
	return &scheduledScalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the scheduledScaler, and returns the corresponding scheduledScaler object, and an error if there is any.
func (c *scheduledScalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScheduledScaler, err error) {
	result = &v1alpha1.ScheduledScaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scheduledscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ScheduledScalers that match those selectors.
func (c *scheduledScalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScheduledScalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ScheduledScalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scheduledscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested scheduledScalers.
func (c *scheduledScalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("scheduledscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a scheduledScaler and creates it.  Returns the server's representation of the scheduledScaler, and an error, if there is any.
func (c *scheduledScalers) Create(ctx context.Context, scheduledScaler *v1alpha1.ScheduledScaler, opts v1.CreateOptions) (result *v1alpha1.ScheduledScaler, err error) {
	result = &v1alpha1.ScheduledScaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("scheduledscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduledScaler).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a scheduledScaler and updates it. Returns the server's representation of the scheduledScaler, and an error, if there is any.
func (c *scheduledScalers) Update(ctx context.Context, scheduledScaler *v1alpha1.ScheduledScaler, opts v1.UpdateOptions) (result *v1alpha1.ScheduledScaler, err error) {
	result = &v1alpha1.ScheduledScaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scheduledscalers").
		Name(scheduledScaler.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(scheduledScaler).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the scheduledScaler and deletes it. Returns an error if one occurs.
func (c *scheduledScalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scheduledscalers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *scheduledScalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scheduledscalers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched scheduledScaler.
func (c *scheduledScalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScheduledScaler, err error) {
	result = &v1alpha1.ScheduledScaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("scheduledscalers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
